locale: 'hr'
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'src/img/uploads' # Media files will be stored in the repo under images/uploads
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Novice' # Used in the UI
    folder: '_posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Naslov', name: 'title', widget: 'string' }
      - { label: 'Slika', name: 'thumbnail', widget: 'image' }
      - { label: 'Besedilo', name: 'body', widget: 'markdown' }
  - name: 'products' # Used in routes, e.g., /admin/collections/blog
    label: 'Storitve' # Used in the UI
    folder: '_products' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'product',
        }
      - { label: 'Ime storitve', name: 'title', widget: 'string' }
      - { label: 'Slika', name: 'image', widget: 'image' }
      - { label: 'Besedilo', name: 'body', widget: 'markdown' }
  - name: 'other' # Used in routes, e.g., /admin/collections/blog
    label: 'Drugo' # Used in the UI
    files:
      - name: 'settings'
        label: 'Nastavitve'
        editor:
          preview: false
        file: '_data/settings.yml'
        fields:
          - { label: Naslov na prvi strani, name: introTitle, widget: string }
          - { label: Naslov za blog, name: blogTitle, widget: string }
          - { label: Povezava na blog, name: blogMore, widget: string }
          - { label: Delovni čas, name: hours, widget: string }
